/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { ThemeConfig } from "../types";

export const THEMES: ThemeConfig[] = [
  {
    id: "emerald",
    name: "پښتو زمرد",
    nameEnglish: "Pashto Emerald",
    primary: "emerald-600",
    primaryDark: "emerald-500",
    accent: "teal-400",
    bgLight: "bg-emerald-50/70",
    bgDark: "bg-[#0b1c15]",
    cardLight: "bg-white/90 backdrop-blur-md border border-emerald-100",
    cardDark: "bg-[#0f281e]/80 backdrop-blur-md border border-emerald-900/40",
    textLight: "text-emerald-950",
    textDark: "text-emerald-50",
    gradientFrom: "from-emerald-600",
    gradientTo: "to-teal-700",
    borderLight: "border-emerald-200",
    borderDark: "border-emerald-800/60"
  },
  {
    id: "gold",
    name: "د بېدیا سره زر",
    nameEnglish: "Desert Gold",
    primary: "amber-500",
    primaryDark: "amber-400",
    accent: "yellow-400",
    bgLight: "bg-amber-50/60",
    bgDark: "bg-[#17130b]",
    cardLight: "bg-white/90 backdrop-blur-md border border-amber-100",
    cardDark: "bg-[#251e12]/80 backdrop-blur-md border border-amber-950/40",
    textLight: "text-amber-950",
    textDark: "text-amber-50",
    gradientFrom: "from-amber-500",
    gradientTo: "to-yellow-600",
    borderLight: "border-amber-200",
    borderDark: "border-amber-900/40"
  },
  {
    id: "sunset",
    name: "د مازیګر لمر",
    nameEnglish: "Sunset Coral",
    primary: "orange-600",
    primaryDark: "orange-500",
    accent: "rose-400",
    bgLight: "bg-orange-50/60",
    bgDark: "bg-[#1a0e0b]",
    cardLight: "bg-white/90 backdrop-blur-md border border-orange-100",
    cardDark: "bg-[#281510]/80 backdrop-blur-md border border-orange-950/40",
    textLight: "text-orange-950",
    textDark: "text-orange-50",
    gradientFrom: "from-orange-600",
    gradientTo: "to-rose-600",
    borderLight: "border-orange-200",
    borderDark: "border-orange-900/40"
  },
  {
    id: "sky",
    name: "شین هسک",
    nameEnglish: "Sky Breeze",
    primary: "sky-600",
    primaryDark: "sky-400",
    accent: "cyan-400",
    bgLight: "bg-sky-50/70",
    bgDark: "bg-[#09151e]",
    cardLight: "bg-white/90 backdrop-blur-md border border-sky-100",
    cardDark: "bg-[#0f2130]/80 backdrop-blur-md border border-sky-900/40",
    textLight: "text-sky-950",
    textDark: "text-sky-50",
    gradientFrom: "from-sky-600",
    gradientTo: "to-cyan-600",
    borderLight: "border-sky-200",
    borderDark: "border-sky-900/40"
  },
  {
    id: "amethyst",
    name: "شاهي ارغوان",
    nameEnglish: "Royal Amethyst",
    primary: "purple-600",
    primaryDark: "purple-500",
    accent: "fuchsia-400",
    bgLight: "bg-purple-50/70",
    bgDark: "bg-[#130b1a]",
    cardLight: "bg-white/90 backdrop-blur-md border border-purple-100",
    cardDark: "bg-[#1f102b]/80 backdrop-blur-md border border-purple-950/40",
    textLight: "text-purple-950",
    textDark: "text-purple-50",
    gradientFrom: "from-purple-600",
    gradientTo: "to-fuchsia-600",
    borderLight: "border-purple-200",
    borderDark: "border-purple-900/40"
  },
  {
    id: "rose",
    name: "رنګین ګلاب",
    nameEnglish: "Rose Petal",
    primary: "rose-600",
    primaryDark: "rose-500",
    accent: "pink-400",
    bgLight: "bg-rose-50/70",
    bgDark: "bg-[#1a0b11]",
    cardLight: "bg-white/90 backdrop-blur-md border border-rose-100",
    cardDark: "bg-[#2b0f1a]/80 backdrop-blur-md border border-rose-950/40",
    textLight: "text-rose-950",
    textDark: "text-rose-50",
    gradientFrom: "from-rose-600",
    gradientTo: "to-pink-600",
    borderLight: "border-rose-200",
    borderDark: "border-rose-900/40"
  },
  {
    id: "autumn",
    name: "سویلي پاڼې",
    nameEnglish: "Autumn Amber",
    primary: "copper-600", // Will map to beautiful brown/amber classes
    primaryDark: "amber-500",
    accent: "orange-400",
    bgLight: "bg-amber-50/50",
    bgDark: "bg-[#18110b]",
    cardLight: "bg-white/90 backdrop-blur-md border border-amber-100",
    cardDark: "bg-[#251b11]/80 backdrop-blur-md border border-amber-900/40",
    textLight: "text-amber-950",
    textDark: "text-amber-50",
    gradientFrom: "from-yellow-700",
    gradientTo: "to-orange-700",
    borderLight: "border-amber-200",
    borderDark: "border-amber-900/40"
  },
  {
    id: "forest",
    name: "د شنه ځنګل سيوري",
    nameEnglish: "Forest Moss",
    primary: "lime-600",
    primaryDark: "lime-500",
    accent: "emerald-400",
    bgLight: "bg-stone-50/70",
    bgDark: "bg-[#0b140b]",
    cardLight: "bg-white/90 backdrop-blur-md border border-zinc-200",
    cardDark: "bg-[#112111]/80 backdrop-blur-md border border-zinc-800/40",
    textLight: "text-stone-900",
    textDark: "text-stone-50",
    gradientFrom: "from-lime-600",
    gradientTo: "to-emerald-700",
    borderLight: "border-zinc-300",
    borderDark: "border-zinc-800/40"
  },
  {
    id: "ocean",
    name: "د اباسین څپې",
    nameEnglish: "Mystic Ocean",
    primary: "teal-600",
    primaryDark: "teal-400",
    accent: "cyan-300",
    bgLight: "bg-teal-50/70",
    bgDark: "bg-[#051416]",
    cardLight: "bg-white/90 backdrop-blur-md border border-teal-100",
    cardDark: "bg-[#082226]/80 backdrop-blur-md border border-teal-950/40",
    textLight: "text-teal-950",
    textDark: "text-teal-50",
    gradientFrom: "from-teal-600",
    gradientTo: "to-cyan-700",
    borderLight: "border-teal-200",
    borderDark: "border-teal-900/40"
  },
  {
    id: "obsidian",
    name: "تور ستوری",
    nameEnglish: "Classic Obsidian",
    primary: "zinc-800",
    primaryDark: "zinc-200",
    accent: "zinc-400",
    bgLight: "bg-zinc-50/90",
    bgDark: "bg-[#09090b]",
    cardLight: "bg-white border border-zinc-200",
    cardDark: "bg-zinc-900 border border-zinc-800",
    textLight: "text-zinc-900",
    textDark: "text-[#fafafa]",
    gradientFrom: "from-zinc-900",
    gradientTo: "to-zinc-800",
    borderLight: "border-zinc-300",
    borderDark: "border-zinc-800"
  }
];

export function getTheme(id: string): ThemeConfig {
  return THEMES.find((theme) => theme.id === id) || THEMES[0];
}
